{{- if .Values.anubis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: anubis-policy
data:
  botPolicies.yaml: |
    bots:
      - import: (data)/crawlers/commoncrawl.yaml
      - import: (data)/bots/_deny-pathological.yaml
      - import: (data)/bots/aggressive-brazilian-scrapers.yaml
      - import: (data)/meta/ai-block-aggressive.yaml
      - import: (data)/crawlers/_allow-good.yaml
      - import: (data)/clients/x-firefox-ai.yaml
      - import: (data)/common/keep-internet-working.yaml
      - name: generic-browser
        user_agent_regex: >-
          Mozilla|Opera
        action: CHALLENGE
        challenge:
          difficulty: 1
          report_as: 4
          algorithm: metarefresh
{{- end }}
